name: mlflow-env
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - fastapi
      - uvicorn
      - scikit-learn
      - joblib
      - pandas
      - numpy
      - mlflow==2.19.0
